version: '3.8'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      - MINIO_SSL=off

    volumes:
      - minio-data:/data

volumes:
  minio-data:
