services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      - MINIO_SSL=off

    volumes:
      - minio-data:/data
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: startpad
    volumes:
      - db-data:/var/lib/postgresql/data
  # srs:
  #   image: ossrs/srs:5
  #   ports:
  #     - "1935:1935"
  #     - "1985:1985"
  #     - "8080:8080"
  #     - "8000:8000/udp"
  #     - "10080:10080/udp"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # moderation:
  #   image: ghcr.io/brahimabd98/moderation_api_py:main
  #   ports:
  #     - "5555:5555"
  #     - "9095:9095"
  #   environment:
  #     DATABASE_URL: redis://localhost:6379/0 

volumes:
  minio-data:
  db-data:
  pgadmin-data:
  redis-data:
